site_name: TermUI
site_description: A modern, declarative, and efficient Terminal UI library for Python

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: "material"
  palette:
    scheme: slate
    primary: teal
  font:
    text: Ubuntu
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - search.suggest

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            modernize_annotations: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_signature_annotations: false
            separate_signature: true
            signature_crossrefs: true
            merge_init_into_class: true
            parameter_headings: true
            show_root_heading: false
            docstring_options:
              ignore_init_summary: true
            show_source: false
            filters:
              - "!^_"
              - "^__init__$"
  - git-revision-date-localized:

watch:
  - mkdocs.yml
  - src/textual

nav:
  - Home: "index.md"
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quickstart.md
      - Concepts: getting-started/concepts.md
  - Guides:
      - Layouts: guides/layouts.md
      - Widgets: guides/widgets.md
      - Theming: guides/theming.md
      - Input Handling: guides/input.md
      - Rendering Model: guides/rendering.md
  - API:
      - "api/index.md"
      - Core:
          - termui.app: "api/app.md"
          - termui.char: "api/char.md"
          - termui.color: "api/color.md"
          - termui.cursor: "api/cursor.md"
          - termui.dom: "api/dom.md"
          - termui.errors: "api/errors.md"
          - termui.events: "api/events.md"
          - termui.layout: "api/layout.md"
          - termui.logger: "api/logger.md"
          - termui.renderer: "api/renderer.md"
          - termui.screen: "api/screen.md"
          - termui.widget: "api/widget.md"
      - Layouts:
          - "api/layouts/vertical.md"
          - "api/layouts/horizontal.md"
          - "api/layouts/grid.md"
      - Widgets:
          - "api/widgets/button.md"
          - "api/widgets/container.md"
          - "api/widgets/text.md"
  - Roadmap: roadmap.md
  - Contributing: contributing.md
  - Changelog: changelog.md

copyright: Copyright &copy; Josh Lawson 2025
