site_name: TermUI Docs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: "material"
  palette:
    scheme: slate
    primary: teal
  font:
    text: Ubuntu
    code: JetBrains Mono
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
    - content.code.annotate
    - content.code.copy

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            modernize_annotations: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_signature_annotations: false
            separate_signature: true
            signature_crossrefs: true
            merge_init_into_class: true
            parameter_headings: true
            show_root_heading: false
            docstring_options:
              ignore_init_summary: true
            show_source: false
            filters:
              - "!^_"
              - "^__init__$"
      watch:
        - mkdocs.yml
        - src/textual
  - git-revision-date-localized:

nav:
  - Home: "index.md"
  - Getting Started: "getting_started.md"
  - Examples:
      - "examples/index.md"
  - API:
      - "api/index.md"
      - Core:
          - "api/app.md"
          - "api/screen.md"
          - DOM: "api/dom.md"
          - "api/renderer.md"
      - Layouts:
          - "api/layouts/vertical.md"
          - "api/layouts/horizontal.md"
          - "api/layouts/grid.md"
      - Widgets:
          - "api/widgets/button.md"
          - "api/widgets/container.md"
          - "api/widgets/text.md"
  - FAQ: faq.md

copyright: Copyright &copy; Josh Lawson 2025
