name: CI / Docs Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    name: Setup Python & Poetry
    runs-on: ubuntu-latest
    outputs:
      poetry-cache: ${{ steps.cache-poetry.outputs.cache-hit }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.6.1"
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry dependencies
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: poetry install --with dev

  lint-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.6.1"

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run Black
        run: poetry run black --check src tests

      - name: Run Pylint
        run: poetry run pylint src

      - name: Run tests
        run: poetry run pytest --maxfail=1 --disable-warnings -q

  docs:
    name: Build & Deploy Docs
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: "1.6.1"

      - name: Install dependencies
        run: poetry install --with dev

      - name: Build docs
        run: poetry run mkdocs build --strict

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true
