name: CI / Docs Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    name: Setup Python & Poetry
    runs-on: ubuntu-latest
    outputs:
      poetry-cache: ${{ steps.cache-poetry.outputs.cache-hit }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python & Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.6.1"

      - name: Cache Poetry dependencies
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: poetry install --with dev

  docs:
    name: Build & Deploy Docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python & Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.6.1"

      - name: Cache Poetry dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: poetry install --with dev

      - name: Build docs
        run: poetry run mkdocs build --strict

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          force_orphan: true
