name: Ruff lint and format

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: astral-sh/ruff-action@v3.5.1
      - name: Run Ruff
        run: |
          ruff check .
          ruff fix .
